exception has occurred: KeyError
(7, 4)
  File "C:\Users\carlos\workspace\ajedrez\piezas_ajedrez.py", line 217, in movimientos_posibles_piezas
    
  File "C:\Users\carlos\workspace\ajedrez\piezas_ajedrez.py", line 245, in rey_es_comido
    for e in movimientos_posibles:
  File "C:\Users\carlos\workspace\ajedrez\piezas_ajedrez.py", line 208, in movimientos_rey
    return movimientos_posibles
  File "C:\Users\carlos\workspace\ajedrez\piezas_ajedrez.py", line 230, in movimientos_posibles_piezas
    return salida
  File "C:\Users\carlos\workspace\ajedrez\ajedrez.py", line 66, in chequear_movimiento
    print("pos_posibles",movimientos_posibles_piezas(tablero,posicion1))
  File "C:\Users\carlos\workspace\ajedrez\main.py", line 26, in <module>
    if chequear_movimiento(tablero,posicion1,posicion2,jugador):